import {
  FiX,
  FiAlertTriangle,
  FiClock,
  FiServer,
  FiGlobe,
  FiShield,
  FiCheckCircle
} from "react-icons/fi";


function AlertInvestigation({
  alert,
  onClose,
  onStatusChange
}) {

  if (!alert) {
    return null;
  }


  const detectedDetection =
  (alert.detections || []).find(
    detection => detection.detected === true
  );


const severity = String(
  alert.severity ||
  detectedDetection?.severity ||
  alert.risk?.level ||
  "UNKNOWN"
).toUpperCase();


const alertTitle =
  alert.type ||
  alert.rule ||
  detectedDetection?.rule ||
  alert.name ||
  "Security Detection";


const alertMessage =
  alert.message ||
  detectedDetection?.message ||
  "Security detection generated by the network defense engine.";


const sourceIP =
  alert.sourceIP ||
  alert.source ||
  alert.src_ip ||
  "Unknown";


const destinationIP =
  alert.destinationIP ||
  alert.destination ||
  alert.dst_ip ||
  "Unknown";


const riskScore =
  typeof alert.riskScore === "number"
    ? alert.riskScore
    : typeof alert.risk === "object"
      ? alert.risk?.score ?? 0
      : Number(alert.risk) || 0;


const mitre =
  detectedDetection?.mitre || null;


  return (

    <div className="investigation-overlay">

      <div className="investigation-panel">


        {/* HEADER */}

        <div className="investigation-header">

          <div>

            <div className="investigation-title">

              <FiAlertTriangle />

              <h2>
                Alert Investigation
              </h2>

            </div>

            <p>
              Security event investigation
            </p>

          </div>


          <button
            className="close-button"
            onClick={onClose}
          >

            <FiX />

          </button>

        </div>


        {/* ALERT SUMMARY */}

        <div className="investigation-summary">

          <div className="alert-main-info">

            <div
              className={`severity-badge severity-${severity.toLowerCase()}`}
            >

              {severity}

            </div>


            <h1>
              {alertTitle}
            </h1>


            <p>
  {alertMessage}
</p>

          </div>


          <div className="risk-display">

            <span>
              RISK SCORE
            </span>

            <strong>
              {riskScore}
            </strong>

            <small>
              / 100
            </small>

          </div>

        </div>


        {/* DETAILS */}

        <div className="investigation-section">

          <h3>
            Alert Details
          </h3>


          <div className="details-grid">


            <div className="detail-item">

              <FiShield />

              <div>

                <span>
                  Detection Rule
                </span>

                <strong>
  {detectedDetection?.rule ||
    alert.rule ||
    alert.detection ||
    alert.type ||
    "Unknown Rule"}
</strong>

              </div>

            </div>


            <div className="detail-item">

              <FiGlobe />

              <div>

                <span>
                  Source IP
                </span>

                <strong>
                  {sourceIP}
                </strong>

              </div>

            </div>


            <div className="detail-item">

              <FiServer />

              <div>

                <span>
                  Destination
                </span>

                <strong>
                  {destinationIP}
                </strong>

              </div>

            </div>


            <div className="detail-item">

              <FiClock />

              <div>

                <span>
                  Timestamp
                </span>

                <strong>
                  {alert.timestamp ||
                    alert.time ||
                    "Unknown"}
                </strong>

              </div>

            </div>

          </div>

        </div>


        {/* DESCRIPTION */}

        <div className="investigation-section">

          <h3>
            Detection Analysis
          </h3>

          <div className="analysis-box">

            <p>

              The detection engine identified
              suspicious activity matching the
              configured security rule.

            </p>

            <p>

              This alert should be reviewed by
              the security analyst to determine
              whether the activity represents
              malicious behavior.

            </p>

          </div>

        </div>

{/* MITRE ATT&CK */}

<div className="investigation-section">

  <h3>
    MITRE ATT&CK
  </h3>

  {mitre ? (

    <div className="mitre-card">

      <div className="details-grid">

        <div className="detail-item">

          <FiShield />

          <div>

            <span>
              Technique ID
            </span>

            <strong>
              {mitre.techniqueId}
            </strong>

          </div>

        </div>


        <div className="detail-item">

          <FiShield />

          <div>

            <span>
              Technique
            </span>

            <strong>
              {mitre.technique}
            </strong>

          </div>

        </div>


        <div className="detail-item">

          <FiShield />

          <div>

            <span>
              Tactic
            </span>

            <strong>
              {mitre.tactic}
            </strong>

          </div>

        </div>

      </div>


      {mitre.description && (

        <div className="analysis-box">

          <p>
            {mitre.description}
          </p>

        </div>

      )}

    </div>

  ) : (

    <div className="analysis-box">

      <p>
        No MITRE ATT&CK mapping is available
        for this detection.
      </p>

    </div>

  )}

</div>

        {/* RELATED EVENTS */}

        <div className="investigation-section">

          <div className="section-title-row">

            <h3>
              Related Events
            </h3>

            <span>
              Correlated activity
            </span>

          </div>


          <div className="timeline">


            <div className="timeline-event">

              <div className="timeline-dot"></div>

              <div>

                <strong>
                  Detection triggered
                </strong>

                <p>
                  Security rule matched
                  suspicious activity.
                </p>

              </div>

            </div>


            <div className="timeline-event">

              <div className="timeline-dot"></div>

              <div>

                <strong>
                  Risk calculated
                </strong>

                <p>
                  Risk score: {riskScore}/100
                </p>

              </div>

            </div>


            <div className="timeline-event">

              <div className="timeline-dot"></div>

              <div>

                <strong>
                  Alert generated
                </strong>

                <p>
                  Alert sent to SOC monitoring.
                </p>

              </div>

            </div>


          </div>

        </div>


        {/* ACTIONS */}

        <div className="investigation-actions">

          <button
            className="action-button acknowledge"
            onClick={() =>
              onStatusChange &&
              onStatusChange("ACKNOWLEDGED")
            }
          >

            <FiCheckCircle />

            Acknowledge

          </button>


          <button
            className="action-button investigate"
            onClick={() =>
              onStatusChange &&
              onStatusChange("INVESTIGATING")
            }
          >

            <FiShield />

            Investigate

          </button>


          <button
            className="action-button resolve"
            onClick={() =>
              onStatusChange &&
              onStatusChange("RESOLVED")
            }
          >

            Resolve

          </button>

        </div>


      </div>

    </div>

  );
}


export default AlertInvestigation;